//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWeek01_MVC.SRC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StudentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnameField;
        
        private int Class1CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StelField;
        
        private int SageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaddressField;
        
        private int SweiField;
        
        private System.DateTime StimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamWeek01_MVC.SRC.Class1 class1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sid {
            get {
                return this.SidField;
            }
            set {
                if ((this.SidField.Equals(value) != true)) {
                    this.SidField = value;
                    this.RaisePropertyChanged("Sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sname {
            get {
                return this.SnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SnameField, value) != true)) {
                    this.SnameField = value;
                    this.RaisePropertyChanged("Sname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Class1Cid {
            get {
                return this.Class1CidField;
            }
            set {
                if ((this.Class1CidField.Equals(value) != true)) {
                    this.Class1CidField = value;
                    this.RaisePropertyChanged("Class1Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Stel {
            get {
                return this.StelField;
            }
            set {
                if ((object.ReferenceEquals(this.StelField, value) != true)) {
                    this.StelField = value;
                    this.RaisePropertyChanged("Stel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Sage {
            get {
                return this.SageField;
            }
            set {
                if ((this.SageField.Equals(value) != true)) {
                    this.SageField = value;
                    this.RaisePropertyChanged("Sage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Saddress {
            get {
                return this.SaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SaddressField, value) != true)) {
                    this.SaddressField = value;
                    this.RaisePropertyChanged("Saddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Swei {
            get {
                return this.SweiField;
            }
            set {
                if ((this.SweiField.Equals(value) != true)) {
                    this.SweiField = value;
                    this.RaisePropertyChanged("Swei");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime Stimes {
            get {
                return this.StimesField;
            }
            set {
                if ((this.StimesField.Equals(value) != true)) {
                    this.StimesField = value;
                    this.RaisePropertyChanged("Stimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ExamWeek01_MVC.SRC.Class1 class1 {
            get {
                return this.class1Field;
            }
            set {
                if ((object.ReferenceEquals(this.class1Field, value) != true)) {
                    this.class1Field = value;
                    this.RaisePropertyChanged("class1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Cid {
            get {
                return this.CidField;
            }
            set {
                if ((this.CidField.Equals(value) != true)) {
                    this.CidField = value;
                    this.RaisePropertyChanged("Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cname {
            get {
                return this.CnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CnameField, value) != true)) {
                    this.CnameField = value;
                    this.RaisePropertyChanged("Cname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRC.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ExamWeek01_MVC.SRC.HelloWorldResponse HelloWorld(ExamWeek01_MVC.SRC.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.HelloWorldResponse> HelloWorldAsync(ExamWeek01_MVC.SRC.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ShowResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Show", ReplyAction="*")]
        ExamWeek01_MVC.SRC.ShowResponse Show(ExamWeek01_MVC.SRC.ShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Show", ReplyAction="*")]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.ShowResponse> ShowAsync(ExamWeek01_MVC.SRC.ShowRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 m 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        ExamWeek01_MVC.SRC.AddResponse Add(ExamWeek01_MVC.SRC.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.AddResponse> AddAsync(ExamWeek01_MVC.SRC.AddRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 FindResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        ExamWeek01_MVC.SRC.FindResponse Find(ExamWeek01_MVC.SRC.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.FindResponse> FindAsync(ExamWeek01_MVC.SRC.FindRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 m 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upt", ReplyAction="*")]
        ExamWeek01_MVC.SRC.UptResponse Upt(ExamWeek01_MVC.SRC.UptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upt", ReplyAction="*")]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.UptResponse> UptAsync(ExamWeek01_MVC.SRC.UptRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Show1Result 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Show1", ReplyAction="*")]
        ExamWeek01_MVC.SRC.Show1Response Show1(ExamWeek01_MVC.SRC.Show1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Show1", ReplyAction="*")]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.Show1Response> Show1Async(ExamWeek01_MVC.SRC.Show1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ExamWeek01_MVC.SRC.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ExamWeek01_MVC.SRC.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Show", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.ShowRequestBody Body;
        
        public ShowRequest() {
        }
        
        public ShowRequest(ExamWeek01_MVC.SRC.ShowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowRequestBody {
        
        public ShowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.ShowResponseBody Body;
        
        public ShowResponse() {
        }
        
        public ShowResponse(ExamWeek01_MVC.SRC.ShowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExamWeek01_MVC.SRC.StudentModel[] ShowResult;
        
        public ShowResponseBody() {
        }
        
        public ShowResponseBody(ExamWeek01_MVC.SRC.StudentModel[] ShowResult) {
            this.ShowResult = ShowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(ExamWeek01_MVC.SRC.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExamWeek01_MVC.SRC.StudentModel m;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(ExamWeek01_MVC.SRC.StudentModel m) {
            this.m = m;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(ExamWeek01_MVC.SRC.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(ExamWeek01_MVC.SRC.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(ExamWeek01_MVC.SRC.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExamWeek01_MVC.SRC.StudentModel FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(ExamWeek01_MVC.SRC.StudentModel FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Upt", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.UptRequestBody Body;
        
        public UptRequest() {
        }
        
        public UptRequest(ExamWeek01_MVC.SRC.UptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExamWeek01_MVC.SRC.StudentModel m;
        
        public UptRequestBody() {
        }
        
        public UptRequestBody(ExamWeek01_MVC.SRC.StudentModel m) {
            this.m = m;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.UptResponseBody Body;
        
        public UptResponse() {
        }
        
        public UptResponse(ExamWeek01_MVC.SRC.UptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UptResult;
        
        public UptResponseBody() {
        }
        
        public UptResponseBody(int UptResult) {
            this.UptResult = UptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Show1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Show1", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.Show1RequestBody Body;
        
        public Show1Request() {
        }
        
        public Show1Request(ExamWeek01_MVC.SRC.Show1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Show1RequestBody {
        
        public Show1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Show1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Show1Response", Namespace="http://tempuri.org/", Order=0)]
        public ExamWeek01_MVC.SRC.Show1ResponseBody Body;
        
        public Show1Response() {
        }
        
        public Show1Response(ExamWeek01_MVC.SRC.Show1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Show1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExamWeek01_MVC.SRC.Class1[] Show1Result;
        
        public Show1ResponseBody() {
        }
        
        public Show1ResponseBody(ExamWeek01_MVC.SRC.Class1[] Show1Result) {
            this.Show1Result = Show1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ExamWeek01_MVC.SRC.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ExamWeek01_MVC.SRC.WebService1Soap>, ExamWeek01_MVC.SRC.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExamWeek01_MVC.SRC.HelloWorldResponse ExamWeek01_MVC.SRC.WebService1Soap.HelloWorld(ExamWeek01_MVC.SRC.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ExamWeek01_MVC.SRC.HelloWorldRequest inValue = new ExamWeek01_MVC.SRC.HelloWorldRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.HelloWorldRequestBody();
            ExamWeek01_MVC.SRC.HelloWorldResponse retVal = ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.HelloWorldResponse> ExamWeek01_MVC.SRC.WebService1Soap.HelloWorldAsync(ExamWeek01_MVC.SRC.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.HelloWorldResponse> HelloWorldAsync() {
            ExamWeek01_MVC.SRC.HelloWorldRequest inValue = new ExamWeek01_MVC.SRC.HelloWorldRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.HelloWorldRequestBody();
            return ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExamWeek01_MVC.SRC.ShowResponse ExamWeek01_MVC.SRC.WebService1Soap.Show(ExamWeek01_MVC.SRC.ShowRequest request) {
            return base.Channel.Show(request);
        }
        
        public ExamWeek01_MVC.SRC.StudentModel[] Show() {
            ExamWeek01_MVC.SRC.ShowRequest inValue = new ExamWeek01_MVC.SRC.ShowRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.ShowRequestBody();
            ExamWeek01_MVC.SRC.ShowResponse retVal = ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).Show(inValue);
            return retVal.Body.ShowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.ShowResponse> ExamWeek01_MVC.SRC.WebService1Soap.ShowAsync(ExamWeek01_MVC.SRC.ShowRequest request) {
            return base.Channel.ShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.ShowResponse> ShowAsync() {
            ExamWeek01_MVC.SRC.ShowRequest inValue = new ExamWeek01_MVC.SRC.ShowRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.ShowRequestBody();
            return ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).ShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExamWeek01_MVC.SRC.AddResponse ExamWeek01_MVC.SRC.WebService1Soap.Add(ExamWeek01_MVC.SRC.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(ExamWeek01_MVC.SRC.StudentModel m) {
            ExamWeek01_MVC.SRC.AddRequest inValue = new ExamWeek01_MVC.SRC.AddRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.AddRequestBody();
            inValue.Body.m = m;
            ExamWeek01_MVC.SRC.AddResponse retVal = ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.AddResponse> ExamWeek01_MVC.SRC.WebService1Soap.AddAsync(ExamWeek01_MVC.SRC.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.AddResponse> AddAsync(ExamWeek01_MVC.SRC.StudentModel m) {
            ExamWeek01_MVC.SRC.AddRequest inValue = new ExamWeek01_MVC.SRC.AddRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.AddRequestBody();
            inValue.Body.m = m;
            return ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExamWeek01_MVC.SRC.FindResponse ExamWeek01_MVC.SRC.WebService1Soap.Find(ExamWeek01_MVC.SRC.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public ExamWeek01_MVC.SRC.StudentModel Find(int id) {
            ExamWeek01_MVC.SRC.FindRequest inValue = new ExamWeek01_MVC.SRC.FindRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.FindRequestBody();
            inValue.Body.id = id;
            ExamWeek01_MVC.SRC.FindResponse retVal = ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.FindResponse> ExamWeek01_MVC.SRC.WebService1Soap.FindAsync(ExamWeek01_MVC.SRC.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.FindResponse> FindAsync(int id) {
            ExamWeek01_MVC.SRC.FindRequest inValue = new ExamWeek01_MVC.SRC.FindRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.FindRequestBody();
            inValue.Body.id = id;
            return ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExamWeek01_MVC.SRC.UptResponse ExamWeek01_MVC.SRC.WebService1Soap.Upt(ExamWeek01_MVC.SRC.UptRequest request) {
            return base.Channel.Upt(request);
        }
        
        public int Upt(ExamWeek01_MVC.SRC.StudentModel m) {
            ExamWeek01_MVC.SRC.UptRequest inValue = new ExamWeek01_MVC.SRC.UptRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.UptRequestBody();
            inValue.Body.m = m;
            ExamWeek01_MVC.SRC.UptResponse retVal = ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).Upt(inValue);
            return retVal.Body.UptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.UptResponse> ExamWeek01_MVC.SRC.WebService1Soap.UptAsync(ExamWeek01_MVC.SRC.UptRequest request) {
            return base.Channel.UptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.UptResponse> UptAsync(ExamWeek01_MVC.SRC.StudentModel m) {
            ExamWeek01_MVC.SRC.UptRequest inValue = new ExamWeek01_MVC.SRC.UptRequest();
            inValue.Body = new ExamWeek01_MVC.SRC.UptRequestBody();
            inValue.Body.m = m;
            return ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).UptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExamWeek01_MVC.SRC.Show1Response ExamWeek01_MVC.SRC.WebService1Soap.Show1(ExamWeek01_MVC.SRC.Show1Request request) {
            return base.Channel.Show1(request);
        }
        
        public ExamWeek01_MVC.SRC.Class1[] Show1() {
            ExamWeek01_MVC.SRC.Show1Request inValue = new ExamWeek01_MVC.SRC.Show1Request();
            inValue.Body = new ExamWeek01_MVC.SRC.Show1RequestBody();
            ExamWeek01_MVC.SRC.Show1Response retVal = ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).Show1(inValue);
            return retVal.Body.Show1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.Show1Response> ExamWeek01_MVC.SRC.WebService1Soap.Show1Async(ExamWeek01_MVC.SRC.Show1Request request) {
            return base.Channel.Show1Async(request);
        }
        
        public System.Threading.Tasks.Task<ExamWeek01_MVC.SRC.Show1Response> Show1Async() {
            ExamWeek01_MVC.SRC.Show1Request inValue = new ExamWeek01_MVC.SRC.Show1Request();
            inValue.Body = new ExamWeek01_MVC.SRC.Show1RequestBody();
            return ((ExamWeek01_MVC.SRC.WebService1Soap)(this)).Show1Async(inValue);
        }
    }
}
